config/routes.rb
Deadstartups::Application.routes.draw do

 resources :startups do
   collection do
     match 'tagged/:tag' => "startups#index", :as => :tagged
   end
 end
 resources :tags

 resources :validations
 
 resources :assumptions
 
 root :to => "startups#index"
 
 
end

app/models/assumption.rb
class Assumption < ActiveRecord::Base
  
  has_many :validations
  has_many :startups, :through => :startups
  
  validates_presence_of :value
  
  scope :named, lambda {|query| 
    criteria = self
    query.split(%r{\s+}).each do |q|
      criteria = criteria.where("value ~* ?", q)
    end
    criteria
  }
  
  
end

app/models/startup.rb
class Startup < ActiveRecord::Base

  attr_accessible :name, :reason, :website, :born, :died, :tag_id_list
  
  validates_presence_of :name, :reason, :born, :died
  validates_format_of :website, :with => URI::regexp(%w(http https))
  
  has_many :validations
  has_many :assumptions, :through => :validations
  
  has_and_belongs_to_many :tags
  
  scope :named, lambda {|query| 
    criteria = self
    query.split(%r{\s+}).each do |q|
      criteria = criteria.where("name ~* ?", q)
    end
    criteria
  }
  
  def tag_id_list
    ""
  end
  
  def tag_id_list=(tags)
    self.tag_ids = tags.split(",")
  end
  
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  
  validates_presence_of :name

  has_and_belongs_to_many :startups
  
  scope :named, lambda {|query| 
    criteria = self
    query.split(%r{\s+}).each do |q|
      criteria = criteria.where("name ~* ?", q)
    end
    criteria
  }
  
end

app/models/validation.rb
class Validation < ActiveRecord::Base
  
  validates_presence_of :how
  
  belongs_to :startup
  belongs_to :assumption
  
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/assumptions_controller.rb
class AssumptionsController < ApplicationController
  
  
  def index
    if params[:q]
      @assumptions = Assumption.named(params[:q])
    else
      @assumptions = Assumption.order("created_at desc").page(params[:page]).per(20)
    end
    respond_to do |format|
      format.html
      format.json { 
        render :json => (@assumptions.map do |tag|
          {:id => tag.id, :name => tag.value}
        end)
      }
    end
  end
  
  def new
    
  end
  
  def create
    assumption = Assumption.create(params[:assumption])
    if assumption.persisted?
      redirect_to assumptions_path
    else
      flash[:errors] = assumption.errors.full_messages;
      redirect_to :new
    end
    
  end
  
end

app/controllers/startups_controller.rb
class StartupsController < ApplicationController
  
  def index
    @startups = Startup.order("created_at desc").page(params[:page]).per(10)
    if params[:tag]
      @startups = @startups.joins(:tags).where(:tags => {:name => params[:tag]})
    end
  end
  
  def create
    @startup = Startup.create(params[:startup])
    unless @startup.persisted?
      flash[:errors] = @startup.errors.full_messages
    end
    redirect_to startups_path
  end
  
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  
  def index
    if params[:q]
      @tags = Tag.named(params[:q])
    else
      @tags = Tag.page(params[:page]).per(20)
    end
    respond_to do |format|
      format.json { 
        render :json => (@tags.map do |tag|
          {:id => tag.id, :name => tag.name}
        end)
      }
    end
  end
  
end

app/controllers/validations_controller.rb
class ValidationsController < ApplicationController
  
  
  def create
    request.format = :js
    @validation = Validation.create(params[:validation])
    unless @validation.persisted?
      puts @validation.errors.inspect
      respond_to do |format|    
        format.js{ head :bad_request }
      end
    else
    
      respond_to do |format|
        format.js
      end
  
    end
    
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/assumptions/_assumption.html.erb
<li>
	<span class="big"><%= assumption.value %></span>
	<div class="assumption-validations">
		<h3><%= assumption.validations.size%> Validations attached to this assumption</h3>
		<ul class="validations">
		<%= render assumption.validations %>
		</ul>
	</div>
</li>

app/views/assumptions/index.html.erb
<div class="new-assumption">
<%= form_for Assumption.new , :html => {:honeypot => true, :class => 'validated'} do |a|%>
	
	<%= a.label :value, 'Assumption (phrase as a statement of fact)'%>
	<div>
	<%= a.text_area :value, :rows => 1, :cols => 100, :class => 'required'%>
	</div>
	<%= a.submit%>
<%end%>


<ul class="assumptions">
<%= render @assumptions%>
</ul>


<div class="examples">
	Some examples of assumptions:
	<ul>
		<li>Friends of users will want to see the users' purchases.</li> 
		<li>Users will spend 15 minutes per day organizing their to-do lists.</li>
		<li>Users will sign up and use a more social email client on a daily basis.</li>
	</ul>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dead Startups</title>

<script type="text/javascript" src="http://use.typekit.com/huh0nyj.js"></script>
<script type="text/javascript">try{Typekit.load();}catch(e){}</script>

  <%= javascript_include_tag :defaults %>
	<%= javascript_include_tag 'jquery.tokeninput.js'%>
	<%= javascript_include_tag 'jquery.validate.min.js'%>
  <%= csrf_meta_tag %>
  <%= stylesheet_link_tag :all %>
</head>
<body>

<div id="main-container">
	<header>
		<h1><%= link_to root_path do %><span class="dead tk-bodedo">Dead</span><span class="normal">Startups</span><%end%></h1>
	<p class="headline">Instead of forgetting them, let's learn from their mistakes.</p>	
	</header>
	
	<span class="navigation">
	<%= link_to startups_path do%>Startups<%end%> | <%= link_to  assumptions_path do%>Assumptions<%end%>
	</span>
	<%=yield%>

</div>

</body>
</html>

app/views/startups/_startup.html.erb
<li class="startup">
	<h3 class="name"><%= startup.name%></h3>
	<h4 class="website"><%= link_to startup.website do %><%= startup.website%><%end%></h4> 
	<h5>Born: <%= startup.born.strftime("%m/%d/%Y")%>, Died: <%= startup.died.strftime("%m/%d/%Y")%></h5>
	<div class="reason newlines"><%= startup.reason%></div>
	<ul class="tags">
		<%= render startup.tags%>
	</ul>
	<h4><%= startup.name%> has <%= pluralize startup.validations.size, "validation"%></h4>
	<ol id="<%= startup.id%>-validations" class="validations">
		<%= render startup.validations%>
	</ol>
	
	
	<h4>Add a new Validation to <%= startup.name%></h4>
	<%= form_for Validation.new, :remote => true, :html => {:honeypot => true, :class => 'validated', :disable_with => 'adding..', :id => "new-validation-#{startup.id}"} do |form| %>
	
		<%= form.hidden_field :startup_id, :value => startup.id %>
		<%= form.text_field :assumption_id, :class => 'assumption-search required'%>
		
		<div class="validation-explanation">
		<div>
		<%= form.label :confirms, "Did #{startup.name} validate this assumption?"%>
		<%= form.check_box :confirms%>
		</div>
		<%= form.label :how, "How did #{startup.name} validate or invalidate this assumption?"%>
		<%= form.text_area :how, :rows => 4, :cols => 100, :class => 'required'%>
		</div>	
		<%= form.submit :class => 'white-button' %>
	<%end%>
</li>

app/views/startups/index.html.erb
<ul class="startups">
<%= render @startups%>
</ul>
<%= paginate @startups%>

<% if flash[:errors]%>
	
	<ul class="errors">
		<% flash[:errors].each do |error|%>
			<li><%= error %></li>
		<%end%>
	</ul>
	
<%end%>

<%= form_for Startup.new, :html => {:honeypot => true, :class => 'validated'} do |form|%>


	<span class="other-fields">
		<%= form.label :name%>
		<%= form.text_field :name , :class => 'required'%>
		<%= form.label :website%>
		<%= form.text_field :website, :class => 'url required', :value => 'http://' %>
		<%= form.label :born%>
		<%= form.text_field :born, :class => 'date required'%>
		<%= form.label :died%>
		<%= form.text_field :died, :class => 'date required'%>
		<%= form.label :tag_id_list, "Tags"%>
		<%= form.text_field :tag_id_list, :id => 'tags', :class => 'required'%>
	</span>
	<span class="reason">
		<%= form.label :reason%>
		<%= form.text_area :reason, :class => 'required'%>
	</span>
	<span class="rip">
	<%= form.submit 'Rest in Peace', :class => 'white-button big'%>
	</span>
<%end%>

app/views/tags/_tag.html.erb
<li class="tag">
	<%= link_to tagged_startups_path(tag.name) do%><%= tag.name%><%end%>
</li>

app/views/validations/_validation.html.erb
<li class="validation">
	
	<h3><span class="scary"><%= validation.startup.name %> <%=validation.confirms ? "Validates:" : "Invalidates:"%></span>  <%= validation.assumption.value%></h3>
	<h5>How?<h5>
	<p><%= validation.how%></p>
	
</li>

app/views/validations/create.js.erb
var validation = $("<span style='background-color:#666'>");
validation.addClass('hidden');
validation.html("<%= escape_javascript(render :partial => @validation) %>");
var startup_validations = $("#<%= @validation.startup.id%>-validations");
startup_validations.append(validation);
validation.fadeIn('slow');